/*
 * generated by Xtext 2.23.0
 */
package com.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SRDSLUiModule extends AbstractSRDSLUiModule {

	public SRDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
