/*
 * generated by Xtext 2.23.0
 */
package com.example.ide;

import com.example.SRDSLRuntimeModule;
import com.example.SRDSLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SRDSLIdeSetup extends SRDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SRDSLRuntimeModule(), new SRDSLIdeModule()));
	}
	
}
