/*
 * generated by Xtext 2.23.0
 */
package com.example;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SRDSLStandaloneSetup extends SRDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new SRDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
